displayName: Spring template
description: Template for building a Spring microservice
tags: ["Java", "Spring",]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "spring"
language: "java"
